services:
  fastapi_app:
    image: fastapi-employee:latest
    build:
      context: .
      dockerfile: fastapi-dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    container_name: employee_app
    networks:
      - app-network

networks:
  app-network:
    external: true