services:
  postgres:
    image: employee-posgres:latest
    build:
      context: .
      dockerfile: posgres-dockerfile
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_DB=Employees
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    container_name: employee_db
    networks:
      - app-network

secrets:
  postgres_password:
    file: ./postgres_password.txt

volumes:
  db-data:

networks:
  app-network:
    driver: bridge